### ISSUE TITLE
This file seems to be missing. I am not able to run the code.

### ISSUE THREAD

**Issue by pramodyn** [yulinliu101/DeepTP#3]
https://github.com/yulinliu101/DeepTP/blob/eeb8b85b7590712d63a629ce0866ff95df72df7c/src/Run_RNN_model_Lite.py#L788

**Comment by pramodyn** [comment]
Could sample results be provided (pkl files) ?

**Comment by yulinliu101** [comment]
Those test files are in the folder "data_sampled/test_*.csv".

**Comment by pramodyn** [comment]
In the Jupyter notebook "Visualize_Generated_Trajectories",
 
NameError: name 'FP_utlize' is not defined

**Comment by yulinliu101** [comment]
Fixed.
